"""PDF tablature renderer using PyMuPDF (fitz).

Generates professional-looking guitar tablature PDFs with:
- String lines with fret numbers
- Adaptive note spacing (proportional to time)
- Multiple systems per page
- Header with title, tuning, note count
"""

from pathlib import Path

import fitz  # PyMuPDF

from .tabber import TabEvent, STANDARD_TUNING, STRING_NAMES

# Technique abbreviations for PDF labels
TECHNIQUE_LABELS = {
    "hammer-on": "h",
    "pull-off": "p",
    "sweep": "sw",
    "slide": "sl",
    "bend": "b",
}

# ---------------------------------------------------------------------------
# Layout constants (A4, points)
# ---------------------------------------------------------------------------
PAGE_WIDTH = 595.28   # A4
PAGE_HEIGHT = 841.89
MARGIN_LEFT = 50
MARGIN_RIGHT = 40
MARGIN_TOP = 55
MARGIN_BOTTOM = 40

STRING_SPACING = 12       # points between tab lines
LABEL_WIDTH = 18          # space for string name labels
MIN_NOTE_GAP = 14         # minimum horizontal gap between note columns
SYSTEM_GAP = 30           # vertical space between systems
HEADER_HEIGHT = 80        # space for title block on first page

FONT_NAME = "Courier"
FONT_SIZE_FRET = 9
FONT_SIZE_LABEL = 9
FONT_SIZE_TITLE = 16
FONT_SIZE_SUBTITLE = 10
FONT_SIZE_FOOTER = 7


def render_pdf(
    events: list[TabEvent],
    output_path: str | Path,
    title: str = "",
    tuning: list[int] = STANDARD_TUNING,
    string_names: list[str] | None = None,
    annotations: list | None = None,
    time_resolution: float = 0.1,
) -> Path:
    """Render tablature events to a PDF file.

    Args:
        events: List of TabEvents from assign_frets().
        output_path: Where to save the PDF.
        title: Song/track title for the header.
        tuning: Open string MIDI pitches.
        string_names: Display labels per string.
        annotations: Optional list of TechniqueAnnotation from llm_analyzer.
        time_resolution: Not used for PDF (uses adaptive spacing).

    Returns:
        Path to the generated PDF.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if string_names is None:
        string_names = STRING_NAMES[:len(tuning)]

    num_strings = len(tuning)
    system_height = STRING_SPACING * (num_strings - 1)
    usable_width = PAGE_WIDTH - MARGIN_LEFT - MARGIN_RIGHT - LABEL_WIDTH

    # Build annotation lookup: event_index -> technique label
    technique_map: dict[int, str] = {}
    if annotations:
        for ann in annotations:
            tech = ann.technique
            label = TECHNIQUE_LABELS.get(tech)
            if label:
                technique_map[ann.event_index] = label

    # Tag each event with its original index so we can look up annotations
    # after splitting into systems (systems contain slices of original events)
    event_indices = list(range(len(events)))

    # Split events into systems based on available width
    systems = _split_into_systems(events, usable_width)

    doc = fitz.open()

    page = doc.new_page(width=PAGE_WIDTH, height=PAGE_HEIGHT)
    y_cursor = MARGIN_TOP

    # Draw header on first page
    if title:
        y_cursor = _draw_header(page, title, tuning, string_names, len(events))

    # Track which global event index each system starts at
    event_offset = 0
    for sys_idx, system_events in enumerate(systems):
        # Check if we need a new page
        needed = system_height + SYSTEM_GAP
        if y_cursor + needed > PAGE_HEIGHT - MARGIN_BOTTOM:
            page = doc.new_page(width=PAGE_WIDTH, height=PAGE_HEIGHT)
            y_cursor = MARGIN_TOP

        # Build per-system technique map using original indices
        sys_technique_map = {
            i: technique_map[event_offset + i]
            for i in range(len(system_events))
            if (event_offset + i) in technique_map
        }

        _draw_system(
            page, y_cursor, system_events,
            num_strings, string_names, usable_width,
            technique_map=sys_technique_map,
        )
        event_offset += len(system_events)
        y_cursor += system_height + SYSTEM_GAP

    # Footer on each page
    for page_idx in range(len(doc)):
        pg = doc[page_idx]
        footer = f"Generated by tab-ripper  |  Page {page_idx + 1}/{len(doc)}"
        pg.insert_text(
            (MARGIN_LEFT, PAGE_HEIGHT - MARGIN_BOTTOM + 15),
            footer,
            fontsize=FONT_SIZE_FOOTER,
            fontname=FONT_NAME,
            color=(0.5, 0.5, 0.5),
        )

    doc.save(str(output_path))
    doc.close()
    return output_path


def _split_into_systems(
    events: list[TabEvent],
    usable_width: float,
) -> list[list[TabEvent]]:
    """Split events into systems (lines) that fit the page width.

    Uses adaptive spacing: time gaps map to horizontal space,
    with a minimum gap per note column.
    """
    if not events:
        return []

    systems: list[list[TabEvent]] = []
    current_system: list[TabEvent] = []
    current_width = 0.0

    for i, event in enumerate(events):
        if not current_system:
            current_system.append(event)
            current_width = MIN_NOTE_GAP
            continue

        # Compute width needed for this note
        time_gap = event.time - current_system[-1].time
        gap_width = _time_to_width(time_gap)

        if current_width + gap_width > usable_width:
            systems.append(current_system)
            current_system = [event]
            current_width = MIN_NOTE_GAP
        else:
            current_system.append(event)
            current_width += gap_width

    if current_system:
        systems.append(current_system)

    return systems


def _time_to_width(time_gap: float) -> float:
    """Convert a time gap (seconds) to horizontal width (points).

    Uses sqrt scaling so fast passages are compact but readable,
    while long gaps don't waste too much space.
    """
    # Clamp minimum
    if time_gap < 0.01:
        return MIN_NOTE_GAP
    # Sqrt scaling: 0.1s -> ~18pt, 0.5s -> ~40pt, 1.0s -> ~56pt
    width = MIN_NOTE_GAP + (time_gap ** 0.5) * 40
    return min(width, 80)  # cap max gap


def _compute_x_positions(
    events: list[TabEvent],
    x_start: float,
    x_end: float,
) -> list[float]:
    """Map events to x positions with adaptive time-proportional spacing."""
    if len(events) <= 1:
        return [x_start]

    # Compute raw gaps
    raw_gaps = []
    for i in range(1, len(events)):
        time_gap = events[i].time - events[i - 1].time
        raw_gaps.append(_time_to_width(time_gap))

    total_raw = sum(raw_gaps)
    usable = x_end - x_start - MIN_NOTE_GAP  # leave room at end

    if total_raw > 0:
        # Scale to fit
        scale = usable / total_raw
        gaps = [g * scale for g in raw_gaps]
        # Enforce minimum
        for i in range(len(gaps)):
            if gaps[i] < MIN_NOTE_GAP:
                gaps[i] = MIN_NOTE_GAP
    else:
        gaps = [MIN_NOTE_GAP] * len(raw_gaps)

    positions = [x_start]
    for g in gaps:
        positions.append(positions[-1] + g)

    return positions


def _draw_header(
    page: fitz.Page,
    title: str,
    tuning: list[int],
    string_names: list[str],
    note_count: int,
) -> float:
    """Draw title and metadata at top of page. Returns y after header."""
    import pretty_midi as pm

    y = MARGIN_TOP + 5

    # Title
    page.insert_text(
        (MARGIN_LEFT, y + FONT_SIZE_TITLE),
        title,
        fontsize=FONT_SIZE_TITLE,
        fontname="Helvetica-Bold",
        color=(0, 0, 0),
    )
    y += FONT_SIZE_TITLE + 8

    # Tuning info
    tuning_str = "Tuning: " + " ".join(string_names) + "  (" + " ".join(
        pm.note_number_to_name(p) for p in tuning
    ) + ")"
    page.insert_text(
        (MARGIN_LEFT, y + FONT_SIZE_SUBTITLE),
        tuning_str,
        fontsize=FONT_SIZE_SUBTITLE,
        fontname="Helvetica",
        color=(0.3, 0.3, 0.3),
    )
    y += FONT_SIZE_SUBTITLE + 4

    info_str = f"{note_count} notes detected"
    page.insert_text(
        (MARGIN_LEFT, y + FONT_SIZE_SUBTITLE),
        info_str,
        fontsize=FONT_SIZE_SUBTITLE,
        fontname="Helvetica",
        color=(0.3, 0.3, 0.3),
    )
    y += FONT_SIZE_SUBTITLE + 15

    # Divider line
    page.draw_line(
        fitz.Point(MARGIN_LEFT, y),
        fitz.Point(PAGE_WIDTH - MARGIN_RIGHT, y),
        width=0.5,
        color=(0.7, 0.7, 0.7),
    )
    y += 15

    return y


def _draw_system(
    page: fitz.Page,
    y_top: float,
    events: list[TabEvent],
    num_strings: int,
    string_names: list[str],
    usable_width: float,
    technique_map: dict[int, str] | None = None,
):
    """Draw one system (set of tab lines with notes) on the page."""
    x_start = MARGIN_LEFT + LABEL_WIDTH
    x_end = PAGE_WIDTH - MARGIN_RIGHT

    # Draw string labels (high string at top)
    for i in range(num_strings):
        display_idx = num_strings - 1 - i  # reverse: high string first
        y = y_top + i * STRING_SPACING
        page.insert_text(
            (MARGIN_LEFT, y + 3),
            string_names[display_idx],
            fontsize=FONT_SIZE_LABEL,
            fontname=FONT_NAME,
            color=(0, 0, 0),
        )

    # Draw horizontal string lines
    for i in range(num_strings):
        y = y_top + i * STRING_SPACING
        page.draw_line(
            fitz.Point(x_start, y),
            fitz.Point(x_end, y),
            width=0.4,
            color=(0.6, 0.6, 0.6),
        )

    # Compute x positions for each event
    x_positions = _compute_x_positions(events, x_start, x_end)

    # Place fret numbers
    for evt_idx, event in enumerate(events):
        x = x_positions[evt_idx]
        for note in event.notes:
            # Row: high string at top (row 0 = highest string)
            row = num_strings - 1 - note.string
            y = y_top + row * STRING_SPACING

            fret_str = str(note.fret)
            text_width = len(fret_str) * 5.4  # approximate char width

            # White background to clear the line behind the number
            rect = fitz.Rect(
                x - 1, y - 5,
                x + text_width + 1, y + 3,
            )
            page.draw_rect(rect, color=None, fill=(1, 1, 1))

            # Draw fret number
            page.insert_text(
                (x, y + 3),
                fret_str,
                fontsize=FONT_SIZE_FRET,
                fontname=FONT_NAME,
                color=(0, 0, 0),
            )

        # Draw technique label above this event (if annotated)
        if technique_map and evt_idx in technique_map:
            label = technique_map[evt_idx]
            # Find the highest note in this event (topmost row = smallest row index)
            if event.notes:
                top_row = min(num_strings - 1 - n.string for n in event.notes)
                label_y = y_top + top_row * STRING_SPACING - 8
                page.insert_text(
                    (x, label_y),
                    label,
                    fontsize=7,
                    fontname=FONT_NAME,
                    color=(0.6, 0.0, 0.0),
                )
